spring:
  application:
    name: beebank
  profiles:
    default: prod
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
